// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWCiyDKqolCjrhO3x6f-rVTL_mjAhJKVE',
    appId: '1:16393244897:web:d977e741db1e4bc392e7a0',
    messagingSenderId: '16393244897',
    projectId: 'whatsapp--backend-20555',
    authDomain: 'whatsapp--backend-20555.firebaseapp.com',
    storageBucket: 'whatsapp--backend-20555.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCuc1emKQQZvwgYnvchyP3UTxQA4f7eJU',
    appId: '1:16393244897:android:1116e8941889b75e92e7a0',
    messagingSenderId: '16393244897',
    projectId: 'whatsapp--backend-20555',
    storageBucket: 'whatsapp--backend-20555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLjaEkEnLP1W_6k8DTg_it65wLcT5IGwM',
    appId: '1:16393244897:ios:70862e1f13641bfd92e7a0',
    messagingSenderId: '16393244897',
    projectId: 'whatsapp--backend-20555',
    storageBucket: 'whatsapp--backend-20555.appspot.com',
    iosClientId: '16393244897-jektu3j130g38d6682pbsbreunqjio1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappFullStack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLjaEkEnLP1W_6k8DTg_it65wLcT5IGwM',
    appId: '1:16393244897:ios:70862e1f13641bfd92e7a0',
    messagingSenderId: '16393244897',
    projectId: 'whatsapp--backend-20555',
    storageBucket: 'whatsapp--backend-20555.appspot.com',
    iosClientId: '16393244897-jektu3j130g38d6682pbsbreunqjio1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappFullStack',
  );
}
